export const shipmentListData = [
  {
    name: '210173066689',
    creation: '2024-01-10 17:09:41.962028',
    modified: '2024-01-31 12:42:46.131331',
    modified_by: 's7saway@brandimic.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG1155',
    origin_area: null,
    origin_city: 'CAIRO',
    sender_phone: null,
    sender_name: 'BBUSINESS FOR DEVELOPMENT',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'CAIRO',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 1',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 0.5,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173066689',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-31',
    posting_time: '17:08:52.979889',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-12-06',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173066690',
    creation: '2024-01-10 17:09:42.119824',
    modified: '2024-01-31 12:42:46.211055',
    modified_by: 's7saway@brandimic.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG1155',
    origin_area: null,
    origin_city: 'CAIRO',
    sender_phone: null,
    sender_name: 'BBUSINESS FOR DEVELOPMENT',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'CAIRO',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 1',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 0.5,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173066690',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-31',
    posting_time: '17:08:52.980165',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-12-06',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173095757',
    creation: '2023-12-11 14:52:02.474971',
    modified: '2024-01-31 12:42:46.254717',
    modified_by: 's7saway@brandimic.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0215',
    origin_area: null,
    origin_city: 'ALEXANDRIA',
    sender_phone: null,
    sender_name: 'MCV',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'ALEXANDRIA',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 2',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 0.5,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173095757',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:52:2.626678',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-13',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173096858',
    creation: '2023-12-11 14:48:47.210806',
    modified: '2024-01-31 12:42:46.309551',
    modified_by: 's7saway@brandimic.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0921',
    origin_area: null,
    origin_city: 'ALEXANDRIA',
    sender_phone: null,
    sender_name: 'SABRINA',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'ALEXANDRIA',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 2',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 0.5,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173096858',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:48:47.361771',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-01',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173096880',
    creation: '2023-12-11 14:52:02.695273',
    modified: '2024-01-31 12:42:46.355313',
    modified_by: 's7saway@brandimic.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0215',
    origin_area: null,
    origin_city: 'ALEXANDRIA',
    sender_phone: null,
    sender_name: 'MCV',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'ALEXANDRIA',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 2',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 0.5,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173096880',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:52:2.845476',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-25',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173097445',
    creation: '2023-12-11 14:52:02.219072',
    modified: '2024-01-31 12:42:46.400636',
    modified_by: 's7saway@brandimic.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0215',
    origin_area: null,
    origin_city: 'ALEXANDRIA',
    sender_phone: null,
    sender_name: 'MCV',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'ALEXANDRIA',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 2',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 0.5,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173097445',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:52:2.435151',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-09',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173099752',
    creation: '2023-12-11 14:48:57.736193',
    modified: '2024-01-31 12:42:46.446158',
    modified_by: 's7saway@brandimic.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0921',
    origin_area: null,
    origin_city: 'ALEXANDRIA',
    sender_phone: null,
    sender_name: 'SABRINA',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'ALEXANDRIA',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 2',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 3.45,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173099752',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:48:57.892731',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-25',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173099763',
    creation: '2024-01-10 17:08:56.257176',
    modified: '2024-01-31 12:42:46.506442',
    modified_by: 's7saway@brandimic.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0215',
    origin_area: null,
    origin_city: 'ALEXANDRIA',
    sender_phone: null,
    sender_name: 'MCV',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'ALEXANDRIA',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 2',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 0.5,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173099763',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-31',
    posting_time: '17:08:52.871077',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-12-02',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173099785',
    creation: '2024-01-10 17:12:24.272239',
    modified: '2024-01-31 12:42:46.548483',
    modified_by: 's7saway@brandimic.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0215',
    origin_area: null,
    origin_city: 'ALEXANDRIA',
    sender_phone: null,
    sender_name: 'MCV',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'ALEXANDRIA',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 2',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 0.5,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173099785',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-31',
    posting_time: '17:08:53.267807',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-12-10',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173099796',
    creation: '2024-01-10 17:16:32.310832',
    modified: '2024-02-05 15:45:05.201574',
    modified_by: 'Administrator',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0215',
    origin_area: null,
    origin_city: 'ALEXANDRIA',
    sender_phone: null,
    sender_name: 'MCV',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'ALEXANDRIA',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 2',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 0.5,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173099796',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments:
      '[{"comment": "PUP is Success", "by": "Administrator", "name": "03ab78479d"}, {"comment": "PUP is Success", "by": "Administrator", "name": "57c7478540"}]',
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-31',
    posting_time: '17:08:53.695224',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-12-27',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173099802',
    creation: '2024-01-10 17:13:36.941380',
    modified: '2024-01-10 17:13:37.021194',
    modified_by: 'omar.sherif@smsaexpress.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0215',
    origin_area: null,
    origin_city: 'ALEXANDRIA',
    sender_phone: null,
    sender_name: 'MCV',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'ALEXANDRIA',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 2',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 0.5,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173099802',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-31',
    posting_time: '17:08:53.400705',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-12-20',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173230057',
    creation: '2023-12-11 14:48:44.021394',
    modified: '2023-12-11 14:48:44.112539',
    modified_by: 'omar.sherif@smsaexpress.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0624',
    origin_area: null,
    origin_city: 'CAIRO',
    sender_phone: null,
    sender_name: 'SPINNEYS EGYPT',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'CAIRO',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 1',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 1.0,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173230057',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:48:44.172314',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-04',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173230068',
    creation: '2023-12-11 14:48:44.350344',
    modified: '2023-12-11 14:48:44.442869',
    modified_by: 'omar.sherif@smsaexpress.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0624',
    origin_area: null,
    origin_city: 'CAIRO',
    sender_phone: null,
    sender_name: 'SPINNEYS EGYPT',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'CAIRO',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 1',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 1.0,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173230068',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:48:44.497184',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-05',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173230079',
    creation: '2023-12-11 14:48:44.512499',
    modified: '2023-12-11 14:48:44.607662',
    modified_by: 'omar.sherif@smsaexpress.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0624',
    origin_area: null,
    origin_city: 'CAIRO',
    sender_phone: null,
    sender_name: 'SPINNEYS EGYPT',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'CAIRO',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 1',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 1.0,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173230079',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:48:44.666164',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-06',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173230080',
    creation: '2023-12-11 14:48:45.203153',
    modified: '2023-12-11 14:48:45.301431',
    modified_by: 'omar.sherif@smsaexpress.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0624',
    origin_area: null,
    origin_city: 'CAIRO',
    sender_phone: null,
    sender_name: 'SPINNEYS EGYPT',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'CAIRO',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 1',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 1.0,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173230080',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:48:45.357204',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-07',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173230090',
    creation: '2023-12-11 14:48:47.638021',
    modified: '2023-12-11 14:48:47.737817',
    modified_by: 'omar.sherif@smsaexpress.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0624',
    origin_area: null,
    origin_city: 'CAIRO',
    sender_phone: null,
    sender_name: 'SPINNEYS EGYPT',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'CAIRO',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 1',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 1.0,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173230090',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:48:47.795307',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-08',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173230107',
    creation: '2023-12-11 14:48:48.546667',
    modified: '2023-12-11 14:48:48.630461',
    modified_by: 'omar.sherif@smsaexpress.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0624',
    origin_area: null,
    origin_city: 'CAIRO',
    sender_phone: null,
    sender_name: 'SPINNEYS EGYPT',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'CAIRO',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 1',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 1.0,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173230107',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:48:48.702413',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-09',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173230118',
    creation: '2023-12-11 14:48:49.085614',
    modified: '2023-12-11 14:48:49.189956',
    modified_by: 'omar.sherif@smsaexpress.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0624',
    origin_area: null,
    origin_city: 'CAIRO',
    sender_phone: null,
    sender_name: 'SPINNEYS EGYPT',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'CAIRO',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 1',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 1.0,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173230118',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:48:49.247876',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-11',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173230129',
    creation: '2023-12-11 14:48:50.313382',
    modified: '2023-12-11 14:48:50.408427',
    modified_by: 'omar.sherif@smsaexpress.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0624',
    origin_area: null,
    origin_city: 'CAIRO',
    sender_phone: null,
    sender_name: 'SPINNEYS EGYPT',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'CAIRO',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 1',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 1.2,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173230129',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:48:50.464137',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-12',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
  {
    name: '210173230130',
    creation: '2023-12-11 14:48:51.280007',
    modified: '2023-12-11 14:48:51.368411',
    modified_by: 'omar.sherif@smsaexpress.com',
    owner: 'omar.sherif@smsaexpress.com',
    docstatus: 1,
    idx: 0,
    sender: 'EG0624',
    origin_area: null,
    origin_city: 'CAIRO',
    sender_phone: null,
    sender_name: 'SPINNEYS EGYPT',
    origin_adress_line_1: null,
    origin_country: 'Egypt',
    sender_address: null,
    origin_address_line2: null,
    origin_state: 'CAIRO',
    consignee: 'Default Consignee',
    destination_area: null,
    destination_city: 'CAIRO',
    consignee_phone: null,
    consignee_name: null,
    destination_address_line_1: null,
    destination_country: 'Egypt',
    consignee_address: null,
    destination_address_line_2: null,
    destination_state: 'CAIRO',
    origin_zone: 'Dom 1',
    destination_zone: 'Dom 1',
    service: null,
    total_weight: 1.0,
    status: 'New Shipment',
    movable_units: null,
    amended_from: null,
    company: 'SMSA EXPRESS',
    cod: 0.0,
    total_cod: 0.0,
    barcode: '210173230130',
    branch: null,
    currency: 'EGP',
    pieces: 1,
    not_available: 0,
    percentage: 0.0,
    total_fees: 0.0,
    awb_terms_template: null,
    awb_terms_and_conditions: null,
    sales_invoice_created: 0,
    _user_tags: null,
    _comments: null,
    _assign: null,
    _liked_by: null,
    geolocation_evkp: null,
    shipping_service: 'Domestic - Corporate',
    delivery_time: null,
    from_client_side: 0,
    destination_branch: null,
    origin_branch: null,
    delivery_due_date: null,
    company_currency: 'EGP',
    exchange_rate: 1.0,
    overdue: 0,
    posting_date: '2023-12-11',
    posting_time: '14:48:51.419145',
    is_returned: 0,
    custodian: null,
    assignee: null,
    closed: 0,
    custodian_commission: 0.0,
    awb_date: '2023-11-13',
    type: null,
    origin_address_line_1: null,
    service_type: null,
    adjusted_cod: 0.0,
  },
];

export const shipmentStatusList = [
  {
    id: 1,
    title: 'Received',
  },
  {
    id: 2,
    title: 'Putaway',
  },
  {
    id: 3,
    title: 'Delivered',
  },
  {
    id: 4,
    title: 'Canceled',
  },
  {
    id: 5,
    title: 'Rejected',
  },
  {
    id: 6,
    title: 'Lost',
  },
  {
    id: 7,
    title: 'On Hold',
  },
];
